### ISSUE TITLE
How do i install it on Fedora?

### ISSUE THREAD

**Issue by formlessdao** [cmiles74/xmltool#12]
Hello, how can i install your tool on Fedora?
Can you give a step by step guide please?

**Comment by cmiles74** [comment]
On the front page, in the "Releases" section, you may click on the most recent release. From there, select the ".tar" file. 🙂

**Comment by formlessdao** [comment]
> On the front page, in the "Releases" section, you may click on the most recent release. From there, select the ".tar" file. slightly_smiling_face

I'm new to Linux. Please make a step by step guide.
What do I need to install and in what order and how do i finally couple those to that tar.gz archive?

**Comment by cmiles74** [comment]
That is a good idea and something that I will consider. Thank you!
